import type { Metadata } from "next";
import { Belleza } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/Header";
import AudioPlayer from "@/components/layouts/beatPlayer";

const belleza = Belleza({
  variable: "--font-belleza",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${belleza.variable} antialiased scroll-smooth`}>
        <Header />
        {children}
        <AudioPlayer />
      </body>
    </html>
  );
}
